### ISSUE TITLE
Target debuffs sometimes stop showing up.

### ISSUE THREAD

**Issue by Nillx** [Backupiseasy/ThreatPlates#321] opened 2022-01-23 22:03 UTC
Noticed that from awhile sometimes my debuffs stop showing on some targets and i have to reload UI to fix it. There are no lua errors.

![Screenshot 2022-01-24 000158](https://user-images.githubusercontent.com/34476875/150699620-757a792c-98c9-45ce-999e-43d862e85e92.png)

**Comment by reranshang** [comment] 2022-01-25 10:43
Same thing happend in Shadowland(retail version). I've tried disabling all other addons yet still have this problem so it's obviously not a compatibility problem.
Here's a vid of that situation
https://anonfiles.com/PcF33fDdx8/2022-01-25_16-44-02_7z
(No password)

**Comment by Backupiseasy** [comment] 2022-01-26 21:04
That is really weird. I‘ll check this. You are running the current 10.2 version, right, not the 10.3 beta version?

**Comment by Nillx** [comment] 2022-01-26 21:12
im using 10.3.0-beta2

**Comment by Backupiseasy** [comment] 2022-01-28 13:42
The Auras widget was heavily changed in 10.3.0-beta, so it's likely that the bug is part of that change. If going back fixes this, that would verify it. You might loose some settings doing that though, not sure.

**Comment by Backupiseasy** [comment] 2022-01-28 14:02
You both have Flashing for expiring auras enabled? Looking at the video, that's me first guess.

**Comment by Nillx** [comment] 2022-01-28 19:37
Mine is disabled.

**Comment by Backupiseasy** [comment] 2022-01-31 19:26
I am still not able to reproduce this error. Can one of you test if this also happens with default settings (like a new profile)? Alternatively, you send me your settings file? With that I would be able to test if it only happens with a particular setting.

**Comment by Nillx** [comment] 2022-01-31 19:38
https://drive.google.com/file/d/1DNU3SWd2sTILjs5qa_mw1x9Rjtw3wFA2/view?usp=sharing

Its a bit difficult to reproduce, its quite random...

**Comment by Backupiseasy** [comment] 2022-02-01 18:13
How random is it? I played with your settings while questing (not long, just a few minutes), but did not run into this bug. Is it something that happens like once in a few hours or every 10 min?

**Comment by Nillx** [comment] 2022-02-01 18:26
Sometimes it never happen sometimes it happen with every other mob. Noticed that its happening quite often in Gruul's lair. Ill try reinstalling the addon but keep my settings and see if that helps.

**Comment by Backupiseasy** [comment] 2022-02-01 18:27
That's the TBC version then, right? Does it happen in Retail as well? reranshang above wrote that it does.

**Comment by Nillx** [comment] 2022-02-01 18:29
Ive never seen it happen in Retail (yet) and i play TBC and Retail. Maybe its happen more often in instances? Ill try to make a video when i see it happen again.

**Comment by Nillx** [comment] 2022-02-02 18:28
Nvm its happening in the outworld too. Also another thing, im using it with this addon https://www.curseforge.com/wow/addons/nameplateauras/files/3320881

 which was updated almost 1 year ago. Now i disabled it and gonna check if its still happening

**Comment by Nillx** [comment] 2022-02-03 20:00
Its happening without that addon so its not that. Made a little video when it was happening https://www.youtube.com/watch?v=pmoAVGyWv30

**Comment by Backupiseasy** [comment] 2022-02-05 08:38
So, from what I can see from the video:
- It's an bug that happens for one nameplate, but not for all - only the bugged one does not work any more, the others work just fine.
- As nameplates are re-used by WoW I assume that once this bug occurs for a nameplate, it cannot recover when it is used again.
- The bug does not happen while the nameplate is active/shown (meaning, the auras do not disapear suddenly), but more like when the nameplate is shown/re-used. Then the auras are not shown from the beginning.
- Based on that, it should be an issue linked to a nameplate being hidden (i.e., when the unit dies) and the nameplate not initialized correctly/fully when it is shown again.

**Comment by Backupiseasy** [comment] 2022-02-05 17:57
I still do not experience this bug myself (I even started leveling my Warlock!), but I checked the sourcecode for the Auras widget and found some code that might hide an auras area (like debuffs), but never show it again (it's, I think, related to nameplates being used for friendly, then for enemy nameplates). I am not sure if this is the reason, but if so, the following version should fix this:
https://drive.google.com/file/d/1IFG-tnXnfUch0fullHtxK9TutxP4NZao/view?usp=sharing

**Comment by Nillx** [comment] 2022-02-05 18:00
Thanks ill install it and see if its still happening.

**Comment by Nillx** [comment] 2022-02-05 18:56
Did all Netherwing dailies and all dots are showing normally with that version. Ill do a proper test tomorrow during our raid.

**Comment by Backupiseasy** [comment] 2022-02-05 19:28
Ah, good to hear. Would be great if the bug is gone with that. Based on my thinking why this could be happening, I might also be able to reproduce the bug and also test if it's gone.

**Comment by Nillx** [comment] 2022-02-05 19:30
I tried dotting everything today to see if its happening but i couldnt reproduce it. Will post again tomorrow after the raid

**Comment by Backupiseasy** [comment] 2022-02-05 19:31
Also just checked: you have CC disabled. With it enabled, the error should also not happen (because the debuff area was only hidden when both, debuff and CC area are disabled). And once it is hidden, it probably was never shown again.
That error should also already be in 10.2, hah.

**Comment by Nillx** [comment] 2022-02-05 19:34
Yeah i had them disabled because i was using NameplateAuras to make CC debuffs big.

**Comment by Backupiseasy** [comment] 2022-02-05 22:07
I finally was able to reproduce this bug and it's fixed with the above version. I guess my assumption above was right. This error occurs when nameplates for friendly units are re-used and the CC area is disabled.

**Comment by Nillx** [comment] 2022-02-06 01:24
Great thanks for spending that much time to fix this!

**Comment by Nillx** [comment] 2022-02-08 13:44
Update. It seems to be fixed, all auras are showing as intended.

**Closed** 2022-06-30 13:12 UTC
Labels: bug
