### ISSUE TITLE
Issues with ennemy Player castbar in wow SOD ?  (pvp,bg,..)

### ISSUE THREAD

**Issue by taoqik** [Backupiseasy/ThreatPlates#493] opened 2023-12-30 08:00 UTC
In pve, I can see ennemy NPC nameplate/castbar but in pvp, ennemy players, I see nameplates but castbar are not showing (example I can't see shaman casting a spell but I can see his totem casting)

**Comment by danjohnso** [comment] 2024-01-16 03:37
Seeing the samething

**Comment by Backupiseasy** [comment] 2024-01-16 19:28
It's a long time since I worked on castbars in WoW Classic. As far as I remember, Classic does not show castbars (with TP disabled and only using WoW default nameplates, you should see not castbars), that's why I use a library for that. I did not update this library for quite some time, maybe it's related to this. But there also seems to be no update, hm.

I can look into that, but I am not sure if I am able to fix it. 

Are only totem nameplates not shown or any nameplates at all?

**Comment by Backupiseasy** [comment] 2024-01-16 19:30
I just googled this a bit. It seems that since patch 1.15.0+, WoW Classic now also shows castbars, so I could remove the additional library. Maybe it works after that. I will check. -

**Comment by danjohnso** [comment] 2024-01-17 14:14
Correct about 1.15+.  Its odd that the castbar works for normal enemies, just not for players.  This is true for both enemy players and friendly players.  I confirmed the even friendly player castbar is shown with the built in option, but not on ThreatPlates

**Comment by PetaZwegat** [comment] 2024-01-22 06:17
Any chance for a fix? Really love TP but cannot use it without those castbars. If there´s any build for testing a fix, i´d love test it. elvui had the same problem, but managed to fix it (if that helps at all).

**Comment by danjohnso** [comment] 2024-01-22 13:58
> Any chance for a fix? Really love TP but cannot use it without those castbars. If there´s any build for testing a fix, i´d love test it. elvui had the same problem, but managed to fix it (if that helps at all).

Looks like this was the commit for ElvUI that modified castbar behavior @Backupiseasy 
https://github.com/tukui-org/ElvUI/commit/2a12fdc79fc00f793f9519f1cf2c6a3b80d1bade

**Comment by danjohnso** [comment] 2024-01-22 14:33
I took a stab at just removing the LibClassicCasterino library but I must be missing something.  I sometimes see the castbar now, but it does not always show, especially on shorter casts.  More details, looks like threat plates does not update unless I change focus away from the person casting.  Maybe I missed something with the update hooks?

https://github.com/danjohnso/ThreatPlates

ElvUI took out the LibClassicDurations library too, not sure if you still want to keep that.

**Comment by Backupiseasy** [comment] 2024-01-22 18:08
The recent changes with path 1.15 only added a cast bar for the (enemy) unit frame, but not for nameplates as fas as I can tell. Which means that LibClassicCasterino is still needed. But I only did some basic testing as I also worked on a bug on retail. This still needs more investigation. 

I am unsure why LibClassicCasterino should not work in PvP situations unless something changed with the combat log.

**Comment by Backupiseasy** [comment] 2024-01-22 18:20
Well, I quickly removed both libraries (Casterino and ClassicDurations) and aura durations as well as castbars are still shown (with some minor adjustments). So, it really seems that these are no longer required. I try to upload a beta version for testing in the upcoming days.

**Comment by PetaZwegat** [comment] 2024-01-22 19:11
If you remove Casterino Spells which channel - like penance - won´t work anymore (UnitChannelInfo Event is bugged).

So it seems we still need casterino for that. There´s a pull request with version which fixes penance (only).

**Comment by Backupiseasy** [comment] 2024-01-22 21:08
> If you remove Casterino Spells which channel - like penance - won´t work anymore (UnitChannelInfo Event is bugged).

Hm, that's not nice. I saw that also (a bugfix comment) in some other addon, but I did not look into this. Just keeping LibCasterino around for this, not sure if that makes sense. I guess I need to look into that in more detail.

**Comment by Nebuchazar** [comment] 2024-01-31 18:27
> > If you remove Casterino Spells which channel - like penance - won´t work anymore (UnitChannelInfo Event is bugged).
> 
> Hm, that's not nice. I saw that also (a bugfix comment) in some other addon, but I did not look into this. Just keeping LibCasterino around for this, not sure if that makes sense. I guess I need to look into that in more detail.

Any chances for a fix soon? SoD phase 2 comes out next week, would be great to have this bug fixed by then.

**Comment by Backupiseasy** [comment] 2024-02-07 12:53
Based on the PR https://github.com/Backupiseasy/ThreatPlates/pull/498 I uploaded a new beta version for 11.1.38 that should fix this issue.: https://www.curseforge.com/wow/addons/tidy-plates-threat-plates/files/5087027. Its till relies on LibClassicCasterino because of the channeld casts issue (https://github.com/Stanzilla/WoWUIBugs/issues/516), but I am working on that as well. 
Feedback is welcome.

**Closed** 2024-09-20 18:36 UTC
Labels: bug
