### ISSUE TITLE
Lua Error with TBC Classic

### ISSUE THREAD

**Issue by Gogo1951** [Backupiseasy/ThreatPlates#345] opened 2022-08-20 03:05 UTC
Message: ...Ons\TidyPlates_ThreatPlates\Widgets\ThreatWidget.lua:394: attempt to concatenate field '?' (a nil value)
Time: Fri Aug 19 17:07:10 2022
Count: 1
Stack: ...Ons\TidyPlates_ThreatPlates\Widgets\ThreatWidget.lua:394: attempt to concatenate field '?' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\ThreatWidget.lua"]:394: in function `UpdateThreatValue'
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\ThreatWidget.lua"]:63: in function `?'
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua"]:47: in function <...ns\TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua:37>

Locals: errMsg = "...Ons\TidyPlates_ThreatPlates\Widgets\ThreatWidget.lua:394: attempt to concatenate field '?' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Backupiseasy** [comment] 2022-08-20 08:09
I cannot reproduce this error currently. Is this the first error message you get - normally there should be several. Also, seeting TSM there in the stacktrace makes we wonder if this is a error caused by TP or just a sideeffect of some other error.

**Comment by Backupiseasy** [comment] 2022-09-03 10:47
Closing this as there was now response and 10.5.0 seems to run fine on Wrath Classic.

**Closed by Backupiseasy** 2022-09-03 10:47 UTC
Labels: bug
